AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: SAM Template
Globals:
  Function:
    Timeout: 30
Resources:
  BaseModuleGyuxe:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: BaseModuleGyuxe/template.yaml
